### ISSUE TITLE
[REQUEST] option to store lightmaps as PNG or JPG to spare our internet and the poor version control data cap

### ISSUE THREAD

**Issue by laurentopia** [guycalledfrank/bakery-issues#23]
My commits are in the hundreds of megabytes these days, sucking up all my internet data cap so I looked into it and found out that the lightmaps that Bakery creates are TGA and they are humongous.
So I ran a little compression to png and saw this
![image](https://user-images.githubusercontent.com/26075468/98504791-b8c80400-220c-11eb-9748-2bf298916544.png)
they're 2.5x smaller
now an option to output jpg would make it even more friendly, which only works if alpha isn't used
![image](https://user-images.githubusercontent.com/26075468/98504876-e319c180-220c-11eb-970a-91883d46f281.png)
WOW!
16x smaller

**Comment by guycalledfrank** [comment]
TGA is used for shadowmasks and directions, main color lightmaps are HDR files.
Indeed TGA can be compressed to PNG. I kept TGA because it's easier to inspect it in Photoshop (alpha channel is shown separately, not as transparency).

Added PNG mode today:
https://github.com/guycalledfrank/bakery-csharp/commit/02069f0f2df7dcba8c767a2523dc8008398c0117
https://github.com/guycalledfrank/bakery-compiled/commit/6b46f89a409f4777dc0ddfbe41ff0feb134f06d8

Currently there is no UI option for that, but you can change it in ftAdditionalConfig.cs:

![image](https://user-images.githubusercontent.com/7008423/98523532-15680500-2287-11eb-958d-af1602f854db.png)

**Comment by laurentopia** [comment]
fantastic I'll update.

**Comment by laurentopia** [comment]
I updated to the github and that setting it's in ftadditionalconfig.cs so I added it
maybe the github latest does not include it yet

**Comment by guycalledfrank** [comment]
The setting is there: https://github.com/guycalledfrank/bakery-csharp/blob/master/Editor/x64/Bakery/scripts/ftAdditionalConfig.cs#L23

**Comment by laurentopia** [comment]
Got it, I must have pressed the wrong button.
Thanks!
