### ISSUE TITLE
[request] an option in bakery lightmap group to change the texel per unit (tpu) on select objects

### ISSUE THREAD

**Issue by laurentopia** [guycalledfrank/bakery-issues#26]
the environment does well at 5tpu but some objects would do better at 10 tpu, like lightmap scale in progressive lightmapper
lightmap group option to set a select tpu would be good for that

**Comment by guycalledfrank** [comment]
It's tricky because lightmap groups' main priority is to fit everything in one map.

Scale in Lightmap on mesh renderers should still work even for an object inside a group (with Pack Atlas mode), but it will act as a relative scale, i.e. objects with larger scale will be larger than others in the altas.

When packing non-grouped objects, texels per unit is the priority, so if objects don't fit, it simply allocates additional atlas. Groups can't do that.

**Comment by laurentopia** [comment]
Understood. So it is ok to keep the Mixed Lighting option in the tab Lighting?

**Comment by guycalledfrank** [comment]
Nothing in the Lighting tab affects Bakery (the only exception is Shadow Color in subtractive mode): https://geom.io/bakery/wiki/index.php?title=FAQ#What_should_I_change_in_Unity_Lighting_window_when_working_with_Bakery.3F
