### ISSUE TITLE
[bug] normal map multiplier is ignored by the light baker in baked normal map mode

### ISSUE THREAD

**Issue by laurentopia** [guycalledfrank/bakery-issues#28]
![image](https://user-images.githubusercontent.com/26075468/98989986-ba304f80-24de-11eb-8864-9b68c83849df.png)
![image](https://user-images.githubusercontent.com/26075468/98989999-c0263080-24de-11eb-9984-94c13f354864.png)
![image](https://user-images.githubusercontent.com/26075468/98990024-c87e6b80-24de-11eb-8da5-dcd3ee250a2d.png)
![image](https://user-images.githubusercontent.com/26075468/98990178-f06dcf00-24de-11eb-9d3d-6b3a33e54749.png)

**Comment by guycalledfrank** [comment]
Not a bug really. The problem is:
- Normal map strength is really just a property of a particular shader.
- Unity does not support exporting normals from shaders to its lightmappers (meta pass doesn't output normals).
- Therefore Bakery simply takes anything named "_BumpMap" (or a similar default name in HDRP/URP) and uses it. It doesn't know if the shader has any multipliers, blending of different normal map layers, procedural normals, etc.
- In case you really want to use custom shader-modified normals, there is a way, but it requires modifying the shader, so Bakery recognizes it,

Documented here: https://geom.io/bakery/wiki/index.php?title=Manual#Normal_mapping
