### ISSUE TITLE
RT should bake skinmesh, only takes on static mesh

### ISSUE THREAD

**Issue by laurentopia** [guycalledfrank/bakery-issues#33]
even though it makes sense it is arbitrary, this case is an example where i want a skinmesh to emit light in its zero position
![image](https://user-images.githubusercontent.com/26075468/99208155-97b76400-2774-11eb-8f2c-497a7bd877d1.png)

**Comment by laurentopia** [comment]
fix:
line 375 if ftBuildLigts.cs
            mesh = obj.GetComponent<MeshFilter>()? obj.GetComponent<MeshFilter>().sharedMesh : obj.GetComponent<SkinnedMeshRenderer>()? obj.GetComponent<SkinnedMeshRenderer>().sharedMesh : null;

**Comment by guycalledfrank** [comment]
Seems like the problem is not RTPreview-related, it's just trying to use a Light Mesh on a skinned mesh. Apparently I never tested it! Thanks for noticing.

Fixed:

https://github.com/guycalledfrank/bakery-csharp/commit/f1bba5b4999d00e29ae4b72f10d1317c571a0949

![image](https://user-images.githubusercontent.com/7008423/99239972-dc8ed980-280c-11eb-9a2c-486ff2d2e0e3.png)
