### ISSUE TITLE
Bakery adding red light on light probes

### ISSUE THREAD

**Issue by Zurigan** [guycalledfrank/bakery-issues#41]
After Bakery 'Render': 
![image](https://user-images.githubusercontent.com/3914073/101699638-58f19280-3a30-11eb-920f-5558bc8416d0.png)

After Progressive 'Generate Lighting':
![image](https://user-images.githubusercontent.com/3914073/101699691-77f02480-3a30-11eb-8d3d-18293f716a94.png)

**Comment by Zurigan** [comment]
This only seems to happen on one of the 3 point lights I have in the scene, makes probes completely unusable.

**Comment by guycalledfrank** [comment]
If you're in L1 light probe mode, the cause is ringing (colors being inverted from the opposite side). Progressive fixes by partially losing directionality (blurring the probe further). But you can:
- Use Legacy light probe mode instead of L1: https://geom.io/bakery/wiki/index.php?title=Manual#Light_probe_mode
- Use Bakery Shader with "Non-linear light probe SH" option which reads the probes in a different way, fixing the ringing: https://geom.io/bakery/wiki/index.php?title=Manual#Bakery_shaders
- Use Volumes instead of the probes: https://geom.io/bakery/wiki/index.php?title=Manual#Bakery_Volume

**Comment by Zurigan** [comment]
Thanks for the insight ... 

a) Isn't usable (throws errors) 
b) I'm using URP, I found the option you mentioned on the Standard Bakery shader ... Is there a URP / ShaderGraph equivalent? Assuming there is a way to do this, the reason for using probes was for performance on mobile platforms - would this be suitable still?
c) Volumes look neat but the 'medium' GPU level of complexity & (presumably) higher texture storage space reqs were putting me off using them for my target devices/platforms.

**Comment by guycalledfrank** [comment]
a) Just fixed (see the issue)
b) Hmm, yeah, I don't have this option for URP for now. But since it's not that hard to add... so here you go, try it (BakeryURPNonLinearLightProbe): https://drive.google.com/file/d/14gKWpEl_adF0euOMHLbGBcF7Fqm310Jb/view?usp=sharing
c) "Medium" is a very coarse estimate, they are still pretty cheap. I'd recommend benchmarking on the actual device. Modern mobiles will have no problems with them.

BTW, if you're not using lots of dynamic point/spot lights and dynamic shadows, there is no performance benefit of using URP over standard RP.

**Comment by Zurigan** [comment]
Much improved with the BakeryURPNonLinearLightProbe shader. 

Before with probes showing:
![image](https://user-images.githubusercontent.com/3914073/101834064-b1876500-3aee-11eb-9af4-ec749c1b6bc9.png)

Before with probes hidden: 
![image](https://user-images.githubusercontent.com/3914073/101833962-8d2b8880-3aee-11eb-86cb-f47436d46c73.png)

After:
![image](https://user-images.githubusercontent.com/3914073/101833892-75540480-3aee-11eb-9dfd-a3fee2fe1338.png)

Still a little more pink than she should be but, again, probably below the level where anyone notices!
