### ISSUE TITLE
Bakery closes scene when rendering.

### ISSUE THREAD

**Issue by Zurigan** [guycalledfrank/bakery-issues#42]
This happens even with 'unload scenes before render' unchecked - The scene closes and a temp one is loaded before switching back to the scene to render. 

This is annoying as Unity collapses the scene hierarchy on load.

**Comment by guycalledfrank** [comment]
Can happen if you're in L1 light probe mode or "occlusion probes" are enabled. The reason for this is that Unity has no way to create a lighting data asset from scratch, so the only solution to initialize a grid of probes is to create an empty scene and force the built-in lightmapper to "bake" it, this initializing the lighting data asset where color values can be later modified. This is a fundamental flaw in the Unity, and I can't fix it; But you can use Volumes instead of the probes, as they don't rely on the engine light probe system and don't need crazy workarounds: https://geom.io/bakery/wiki/index.php?title=Manual#Bakery_Volume

**Comment by Zurigan** [comment]
Understood - maybe you could add this explanation to the 'unload scenes before render' tooltip.
