### ISSUE TITLE
RT AO intensity capped at 1

### ISSUE THREAD

**Issue by laurentopia** [guycalledfrank/bakery-issues#79]
![image](https://user-images.githubusercontent.com/26075468/114285446-2d95a900-9a0c-11eb-88b9-84ec8fd583f8.png)
![image](https://user-images.githubusercontent.com/26075468/114285448-35554d80-9a0c-11eb-8c9f-f9bfc9124e74.png)

**Comment by guycalledfrank** [comment]
Yeah it in fact works the same as in the lightmapper itself....

**Comment by laurentopia** [comment]
the baker goes beyond 1 in AO:
![image](https://user-images.githubusercontent.com/26075468/114289616-46af5180-9a2e-11eb-96de-294ee61d9d85.png)
![image](https://user-images.githubusercontent.com/26075468/114289639-7c543a80-9a2e-11eb-99f2-1a77ff9e905f.png)

**Comment by guycalledfrank** [comment]
Sorry, my mistake. The scene I tested didn't have enough crevices, so I didn't see such a difference.
Turns out, implementing proper intensity extrapolation is harder than I thought for the preview, since there is only 1 binary sample per frame, and you can't extrapolate when it's either 0 or 1.
Anyway, implemented it properly now:
https://github.com/guycalledfrank/bakery-compiled/commit/597cb021d697b3e7ff489b6495da65c932c2e652
https://github.com/guycalledfrank/bakery-rtpreview-csharp/commit/44a8d45b0425f6294850db09bba8739c49daeb64

**Comment by laurentopia** [comment]
hmm, now i'm getting this error when doing a preview in the scene view and the stand alone window
![image](https://user-images.githubusercontent.com/26075468/115297620-417a9280-a111-11eb-977e-167981d942eb.png)

**Comment by guycalledfrank** [comment]
Make sure to update from both bakery-compiled and bakery-rtpreview-csharp. Looks like you didn't update from one of them.
